Enhanced retry mechanism & test case added
facebook/facebook-nodejs-business-sdk pull request #295
Opened 2024-09-05 00:50 UTC by fary58

Improved the retry mechanism in VideoUploadTransferRequestManager with exponential backoff to handle transient errors more effectively.
Integrated unit tests to verify the retry logic and ensure robust error handling during the video upload process.

2024-09-05 02:26 UTC, stcheng commented
@fary58 thank you so much for contributing to improve the code quality. could you sign the CLA as well?

2024-09-05 02:31 UTC, stcheng requested changes
I noticed that you have changed all the single quotes to double quotes. While the repository is not consistent everywhere, we primarily use single quotes. Could you remove this quote change from the pull request to maintain the current code style and make the review process easier?

2024-09-05 02:34 UTC, fary58 commented
Hi,

Yes l I'll make the changes.

Regards

On Thu, 5 Sep 2024 at 03:32, Shuotian Cheng ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I noticed that you have changed all the single quotes to double quotes.
> While the repository is not consistent everywhere, we primarily use single
> quotes. Could you remove this quote change from the pull request to
> maintain the current code style and make the review process easier?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/facebook/facebook-nodejs-business-sdk/pull/295#pullrequestreview-2281738407>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APQFYHJL62WA3XC6WZA6OU3ZU67CTAVCNFSM6AAAAABNVMNZ4CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOBRG4ZTQNBQG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2024-12-19 23:09 UTC, stcheng approved these changes
lgtm could you update the pr again? thx

2024-12-19 23:09 UTC, stcheng commented on src/api.js
> +        console.error('Response:', response);
could you remove these two lines of changes? the api.js file is heavily used and could have bigger impact.

2024-12-19 23:09 UTC, stcheng commented on src/video-uploader.js
> +
could you remove the empty spaces?

2025-04-27 03:39 UTC, closed without merging